name: Compilar Nintendont

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar el código
        uses: actions/checkout@v4

      - name: Compilar
        run: |
          docker run --rm --volume="$PWD":/work --workdir=/work henriquegemignani/docker-devkitpro-nintendont bash -c "chmod +x Build.sh && ./Build.sh"

      - name: Guardar el resultado
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nintendont-build
          path: |
            **/*.dol
